---
namespace: community
name: kubernetes_role
version: 1.0.0
readme: README.md
authors: Group3
description: Install kubernetes
license_file: COPYING
tags:
  - v1
repository: https://github.com/projetajc-group3/kubernetes_role.git
documentation: https://github.com/projetajc-group3/kubernetes_role.git
homepage: https://github.com/projetajc-group3/kubernetes_role.git
issues: https://github.com/projetajc-group3/kubernetes_role.git
build_ignore:
  - .gitignore
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
